services:
  db:
    image: postgres:16-alpine
    container_name: movierate_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/script.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    container_name: movierate_backend
    restart: unless-stopped
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:3001
      ConnectionStrings__DbConnection: 'Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}'
    ports:
      - '3001:3001'
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL_CLIENT: http://localhost:3001
    container_name: movierate_frontend
    restart: unless-stopped
    environment:
      - API_URL_SERVER=http://backend:3001
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  postgres_data:
